### ISSUE TITLE
feat: deploy contract to Polygon Mainnet and cast functions for test purposes on the front-end

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-contracts#10]
Proposal:
- Deploy the contract to Polygon
- Create CoreTeam Id
- Create PodLabs leaders Id
- Create PodLabs members Id
- Set the operators
- - CoreTeam and PodLabs should be allowed on every function that involves tasks
- - Members should be allowed to use the `startTask` and `reviewTask`
- Create 50 tasks

**Comment by RafaDSan** [comment]
Hey, I am interested in this task!

**Comment by Guboehm** [comment]
I`ll add a script to create 50 tasks.
