### ISSUE TITLE
feat: unify all contract interfaces in a single file

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-contracts#11]
Proposal:
We have a lot of contracts in the ecosystem, and we want to initiate only one interface instead of more instances of the contract for each interface... e.g.:

```
export const contract = new ethers.Contract(
  contractAddress.Web3Task,
  Web3TaskContract.abi,
  signer
);

export const TaskManagerContract = new ethers.Contract(
  contractAddress.Web3Task,
  TasksManager.abi,
  signer
);
```

We would like an architecture logic to allow for a single ABI from TasksManager which implements the Web3Task contract to carry all the ABI needed for implementations.

Please help discuss and formalize this request

**Comment by danzoniel** [comment]
I am interested in this task! @0xneves

**Comment by RafaDSan** [comment]
Starting this task at 08/10/2023

**Comment by RafaDSan** [comment]
I think we could create a new contract which will unify the interfaces. e.g:

`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./Web3Task.sol";
import "./TasksManager.sol";

contract unifiedContract is Web3Task, TasksManager {

}` 

And we could call it as such:

`export const unifiedContract = new ethers.Contract(
  contractAddress.unifiedContract,
  unifiedContract.abi,
  signer
);`

What do you think @0xneves ?

**Comment by RafaDSan** [comment]
I tested the unified ABI with @heronlancellot and it worked fine without any updates on the smart contracts. 
Can I close this issue or do you want to review it? @0xneves

**Comment by 0xneves** [comment]
The proposal would change the architecture in a way that the main task mapping would be compromised as a child element. Siblings would make it more complicated to understand. Creating a contract just to unify doesn't make much sense but rather just directly accessing it must throughout good architecture. 

Since TasksManager implements Web3Task in the current method, but the Web3Task is the one with an Interface... The correct move would be to create an Interface for TasksManager and import the IWeb3Task.sol. 

This would provide access to all of Web3Tasks functions when calling only the TasksManager and avoids the need for any new contract to be proxied.
