### ISSUE TITLE
add: missing unit tests for all the features implemented since the merge of develop to main

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-contracts#12]
Proposal:
Check all the functions, and create unitary tests for them. Unitary tests is when you check every possible usacase for that following function with different inputs while expecting deterministic behaviors to happen...

An example of this would be:
- Do something as contract Owner and expect it to pass
- Do something not being contract Owner and expects it to fail

Most function are already set, but some of them don't have this mechanism yet, so please go nuts and help us test all the possible cases cenarios

**Comment by RafaDSan** [comment]
I am interested in this task!
