### ISSUE TITLE
feat: integrate subgraph api into the front-end as a library

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-contracts#43]
We just need a typescript file that can be fetched from the subgraph.

Then, it should be reproduced in the rest of the contract when needed. 

We recommend trying to first detect if the connected wallet has tags, and then display accordingly.

**Comment by RafaDSan** [comment]
This issue is duplicated from #153 contract-frontend. 
What is the procedure for this situation, can I just delete it? @0xneves
