### ISSUE TITLE
feat: Estabilish a default Code Styling/Code Formatting

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-contracts#48]
As the Web3Task project may receive more integrants to contribute to the project over time, it may be of mutual interest to establish a default Code Formatting to the visual studio, which is the default coding tool for Web3Task.

This would lead to comprehensive code and standardized patterns, improving reading time and cutting down the adjusting time.

For example:
If someone new clones a repository and starts building on it, its VisualStudio default configuration could format the file in a way that is not according to the patterns, modifying the entire file and therefore making it harder to read the diff file when a pull request is initiated.

**Comment by 0xneves** [comment]
This was added in #45
