### ISSUE TITLE
fix: Remove the text about the format pattern in the README.md file.

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-contracts#51]
Remove the following topic from the README.md file:

Setting Up A Stanrdad Formatting Code
Install the Prettier - Code Formatter in the VsCode extension with esbenp.prettier-vscode.

Modify the settings json.

2.1. Press ctrl + shift + p to oppen the command pallets.
2.2. Type "Open Settings (JSON)".
2.3. Add the following lines to the JSON file:
"[solidity]": {
"editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
},
    "[typescript]": {
   "editor.defaultFormatter": "esbenp.prettier-vscode"
}

**Comment by 0xneves** [comment]
issue was solved
