### ISSUE TITLE
update: Update the `feature/subgraph` branch to be up to date with the `dev` branch.

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-contracts#52]
Update the the branch `feature/subgraph` to be up to date with `dev` branch, so the branch is ready to use and the subgraph does not get outdated.

**Comment by 0xneves** [comment]
Moving this to TODO as there is no PR`s attached

**Comment by RafaDSan** [comment]
Att: PR #53 it was created but not attached, now it is corrected attatched.

**Comment by Guboehm** [comment]
Updated at:  _Originally posted by @RafaDSan in https://github.com/w3b3d3v/web3task-contracts/pull/53#discussion_r1500040223_

**Comment by Guboehm** [comment]
It will be deprecated and we will migrate to ponder framework.
https://github.com/w3b3d3v/web3task-contracts/issues/59
