### ISSUE TITLE
fix: workflow of testnet

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-contracts#54]
Proposal:

- Use this issue to review the workflow of the MvP in the testnet.
- Comment on here all the steps used.
- Comment on any needed changes and provide PR for so or request help by marking @0xneves .
- Check the entire workflow from being a regular user with no access to the dapp, receiving admin privileges, creating tasks, accepting, reviewing, and finishing tasks. Also, be able to configure the application.

**Comment by 0xneves** [comment]
Hey @Guboehm, how is the task going? Can I provide assistance somehow?

**Comment by Guboehm** [comment]
I finished implementing the testnet contracts and the frontend adjustments.
They are available at: https://test-web3task.vercel.app/
The step by step description is pending for next week.

**Comment by Guboehm** [comment]
Lading Page::
[Production](https://web3task.w3d.community/)
[Staging](https://staging.web3task.w3d.community/)

Dapp:
[Production](https://staging.app.web3task.w3d.community/)
[Staging](https://app.web3task.w3d.community/)
