### ISSUE TITLE
feat:  Migration of Subgraph to Ponder

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-contracts#59]
We are going to change the Subgraph for Ponder due to:

- Better scalability with pagination cursors instead of offset
- Easier to use locally as there is no need to run docker locally
- Faster than Subgraph
- We have access to the Database.

## Definition of done:

- [x] Create a branch called `ponder` in web3task-contracts 
- [x] Remove the files regarding the subgraph
- [x] Initiate a ponder project 
- [ ] Refactor the schema and the indexing functions

**Comment by Guboehm** [comment]
It`s in progress

**Comment by Guboehm** [comment]
@RafaDSan Any progress ?

**Comment by RafaDSan** [comment]
I accidentally pushed the commits directly into the [feature/ponder](https://github.com/w3b3d3v/web3task-contracts/tree/feature/ponder) branch, so there it no PR.

Also, I suggest we open a new issue for the "Refactor the schema and the indexing functions"  which will take more time and will be more difficult to do so. What do you think? We can leave this open and make this one like a child issue.

I am sorry for the delayed task. I will be faster with the following ones! 
@Guboehm

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
